# Generated by Django 2.0.5 on 2018-05-31 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Zimbabwe', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BGL Laboratory', 'BGL Laboratory'), ('Haematology', 'Haematology'), ('Chemistry', 'Chemistry'), ('Bacteriology', 'Bacteriology'), ('Parasitology', 'Parasitology'), ('Blood Bank', 'Blood Bank'), ('Histopathology', 'Histopathology'), ('HIV', 'HIV'), ('Immunology', 'Immunology'), ('Serology', 'Serology'), ('Immuno-Hematology', 'Immuno-Hematology')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bulawayo Group Laboratory', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('country', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='laboratory.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.ForeignKey(default='Zimbabwe', on_delete=django.db.models.deletion.PROTECT, to='laboratory.Country')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='laboratory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='laboratory.Laboratory'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='laboratory',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('laboratory', 'name')},
        ),
    ]
