# Generated by Django 2.0.5 on 2018-06-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvFile',
        ),
    ]
