# Generated by Django 2.0.5 on 2018-05-31 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('TRANSFER IN', 'TRANSFER IN'), ('TRANSFER OUT', 'TRANSFER OUT'), ('DAMAGED', 'DAMAGED'), ('EXPIRED', 'EXPIRED'), ('THEFT', 'THEFT'), ('LOSS', 'LOSS')], max_length=15)),
                ('adjust', models.IntegerField(default=0)),
                ('adjustment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(default='')),
                ('adjustment_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_adjustment', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued', models.IntegerField(default=0)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dpt_issued_to', to='laboratory.Department')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_transaction', to='products.Product')),
                ('transaction_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
