# Generated by Django 2.0.5 on 2018-06-01 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0001_initial'),
        ('products', '0001_initial'),
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('EDITED', 'EDITED'), ('REVERTED', 'REVERTED')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PrioritySate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('NORMAL', 'NORMAL'), ('URGENT', 'URGENT')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='orderplacement',
            name='order_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movements.PrioritySate'),
        ),
        migrations.AddField(
            model_name='orderplacement',
            name='ordering_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_from', to='laboratory.Department'),
        ),
        migrations.AddField(
            model_name='orderplacement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_order', to='products.Product'),
        ),
    ]
