# Generated by Django 2.0.5 on 2018-06-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_auto_20180601_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjustment',
            options={'ordering': ('-adjustment_date',)},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date_issued',)},
        ),
    ]
