# Generated by Django 2.0.5 on 2018-06-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0003_auto_20180603_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplacement',
            name='order_by',
        ),
        migrations.RemoveField(
            model_name='orderplacement',
            name='order_priority',
        ),
        migrations.RemoveField(
            model_name='orderplacement',
            name='ordering_dept',
        ),
        migrations.RemoveField(
            model_name='orderplacement',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderState',
        ),
        migrations.DeleteModel(
            name='OrderPlacement',
        ),
        migrations.DeleteModel(
            name='PrioritySate',
        ),
    ]
