# Generated by Django 2.0.5 on 2018-05-31 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Consumables', 'Consumables'), ('Reagents', 'Reagents'), ('Durables', 'Durables')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Caution', 'Caution'), ('Toxic', 'Toxic'), ('Very Toxic', 'Very Toxic'), ('Corrosive', 'Corrosive'), ('Irritant', 'Irritant'), ('Harmful', 'Harmful'), ('Flammable', 'Flammable'), ('Highly Flammable', 'Highly Flammable'), ('Biological', 'Biological'), ('Electrical', 'Electrical'), ('Explosive', 'Explosive'), ('Oxidising', 'Oxidising'), ('Environmental', 'Environmental'), ('Reactive', ' Reactive'), ('Physical', 'Physical'), ('Mechanical', 'Mechanical')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('departments', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='item_from', to='laboratory.Department')),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('box', 'box'), ('container', 'container'), ('bag', 'bag'), ('plastic', 'plastic'), ('bottle', 'bottle'), ('bucket', 'bucket'), ('tray', 'tray'), ('crate', 'crate'), ('bin', 'bin'), ('pouche', 'pouche'), ('envelope', 'envelope'), ('kit', 'kit'), ('cardboard', 'cardboard')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('size', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_received', models.IntegerField(default=0)),
                ('minimum_level', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
                ('department', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='product_from', to='laboratory.Department')),
                ('hazard', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Hazard')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Item')),
                ('packaging', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.PackageType')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ManyToManyField(related_name='product_bin', to='laboratory.Store')),
                ('supplier', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='department_supplier', to='laboratory.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('l', 'liter'), ('ml', 'milliliter'), ('kg', 'kilogramme'), ('g', 'gramme'), ('mg', 'milligramme'), ('ea', 'each'), ('pc', 'piece'), ('t', 'tonne'), ('in', 'inch'), ('cm', 'centimeter'), ('m', 'meter'), ('g', 'gallon'), ('tests', 'tests'), ('kit', 'kit')], max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='products.Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'lot_number')},
        ),
    ]
