# Generated by Django 2.0.5 on 2018-06-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='remaining',
        ),
    ]
