# Generated by Django 2.0.5 on 2018-06-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('products', '0004_product_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_bin', to='laboratory.Store'),
            preserve_default=False,
        ),
    ]
